# /// script
# requires-python = ">=3.12"
# dependencies = ["torch", "transformers>=5.8", "accelerate", "huggingface_hub"]
# ///
from jev import Jev

DIM, RESET = "\033[2m", "\033[0m"
PARAGRAPHS = [
    "INCIDENT REPORT INC-4471, checkout latency and partial payment failures in eu-central-1. Severity SEV-2, declared 2026-03-14 13:58 UTC, mitigated 15:41 UTC, closed 18:20 UTC. Incident commander R. Osei, communications lead M. Fuentes, scribe D. Park. Services involved: checkout-api v2026.3.9, payment-router v2026.2.31, ledger-write v2026.3.2, the feature-flag service v2026.1.14, and the shared Postgres cluster pg-eu-3. Customer-visible symptom: between 13:41 and 15:41 UTC a fraction of checkout attempts in eu-central-1 returned HTTP 502 after a 30 second gateway timeout, and a smaller fraction returned HTTP 200 with an order confirmation while the payment authorization had in fact failed. Estimated 18,400 failed checkout attempts and 212 orders confirmed to the customer without a captured payment. No customer payment data was exposed and no duplicate charges were issued. us-east-1 and ap-southeast-1 were unaffected throughout, and a synthetic canary in eu-west-1 stayed green because it targets a different gateway pool. This report is the reviewed version approved in the incident review meeting of 2026-03-19; it supersedes the draft circulated on 2026-03-15, which reported 204 rather than 212 uncaptured orders.",
    "TIMELINE, all times UTC. 13:31 a scheduled configuration rollout enabled the flag checkout_router_v3_shadow at 5 percent in eu-central-1; the rollout was approved in change ticket CHG-9912 and was expected to be a no-op read path. 13:37 the pg-eu-3 primary connection count rose from a baseline of 480 to 1,900. 13:41 the first customer reports of slow checkout arrived through the support queue; the on-call SRE for checkout was paged at 13:44 by the p99-latency alert after four minutes of sustained breach. 13:47 the on-call acknowledged the page and opened the incident channel. 13:52 the payment-router error rate crossed 8 percent and the automatic circuit breaker opened for the authorization dependency, which by design fails closed but was misconfigured to fail open in eu-central-1 only. 13:58 the on-call declared SEV-2 and R. Osei took command. 14:02 the team observed that pg-eu-3 was saturated on connections rather than CPU, which sat at 41 percent, and that the dominant wait event was the LWLock buffer_mapping. 14:09 a first hypothesis blamed the nightly analytics export; that job was confirmed idle and the hypothesis was dropped at 14:15.",
    "14:18 the team failed read traffic over to the pg-eu-3 replica, which reduced 502 responses from 14 percent to 9 percent but did not resolve them. 14:22 the first database engineer joined the incident channel. 14:26 M. Fuentes published the first status page notice acknowledging degraded checkout in Europe. 14:31 a second hypothesis identified the new shadow router as the source of the extra connections; the flag change was not visible in the incident timeline dashboard because flag events are written to a separate audit log that the dashboard does not query. 14:38 the team located CHG-9912 by hand and saw the 13:31 rollout. 14:44 the flag was set back to 0 percent. 14:47 the connection count began to fall, reaching 620 by 14:55. 15:02 502 responses dropped below 1 percent. 15:08 the team noticed the second symptom, orders confirmed without a captured payment, caused by the circuit breaker failing open while checkout-api treated an open breaker as an approval. 15:19 a hotfix was deployed that treats an open breaker as a decline. 15:41 error rates and confirmation correctness both returned to baseline and the incident was mitigated. 16:05 the 212 affected orders were identified from the ledger and placed on hold. 18:20 all 212 were either re-authorized successfully or cancelled with an apology email, and the incident was closed.",
    "IMPACT. 18,400 failed checkout attempts, of which 11,100 were retried successfully by the customer inside the incident window. Estimated lost revenue 84,000 EUR, of which 61,000 EUR was recovered through follow-up emails within 48 hours. Of the 212 orders confirmed without a captured payment, 173 were re-authorized on the original card and 39 were cancelled. Zero chargebacks were filed. No duplicate charges and no double shipments occurred, because the fulfilment pipeline holds orders for 30 minutes before release and the hold list was applied at 16:05, inside that window for every affected order. Support received 1,240 contacts with an average first response of 41 minutes against a 15 minute target. The status page was updated three times, at 14:26, 15:10 and 15:45. Two enterprise customers invoked their SLA clause and both credits were approved on 2026-03-17. No data was lost in the ledger, and ledger-write never returned a successful write for an uncaptured payment, which is the only reason the 212 orders could be reconstructed exactly.",
    "ROOT CAUSE. The shadow router opened one new Postgres connection per request instead of borrowing from the shared pool. The pool library was initialized inside the request handler rather than at process start, a mistake introduced when the router was copied from a batch job template where a per-invocation pool is correct. At 5 percent of eu-central-1 traffic this added roughly 1,400 concurrent connections, exhausted the pg-eu-3 connection limit of 2,000, and starved checkout-api and ledger-write of connections; that starvation produced the 30 second gateway timeouts. The second symptom had an independent cause that the first symptom merely exposed: the authorization circuit breaker in eu-central-1 carried a fail_open=true override added during a load test in January 2026 and never reverted, and checkout-api interpreted a breaker-open response as an approval rather than as an unknown outcome. Neither the connection leak nor the fail-open override was caught by the staging environment, which runs a single application instance against a Postgres with a connection limit of 100 and therefore reaches that limit only under a load profile staging never generates.",
    "WHAT WENT WELL AND WHAT DID NOT. The hold-and-release design of the fulfilment pipeline bounded the blast radius of the second symptom to a reconciliation task rather than a shipping loss, and the ledger refusing to record uncaptured payments made the affected order set exact rather than estimated. Command handoff was clean and the scribe log was complete enough to write this report without reconstructing timestamps from logs. What did not go well: the team spent 37 minutes on database-side hypotheses because the runbook and the dashboard both pointed there, the status page notice came 45 minutes after the first customer report, and nobody checked the change calendar until 14:38 even though a rollout had been approved for that hour. The review meeting explicitly declined to add a blanket freeze on payment-path rollouts, on the grounds that the failure was a pooling bug and a stale override, not the rollout process itself.",
    "CONTRIBUTING FACTORS AND DETECTION. Flag rollouts are not shown on the incident timeline dashboard, which cost 13 minutes between the first hypothesis and the discovery of CHG-9912. A connection-count alert existed but was routed to the database team channel rather than to the checkout on-call, and no database engineer was in the incident channel until 14:22. The runbook for checkout latency lists database CPU and disk but not connection saturation. Detection was by customer report at 13:41 and by automated alert at 13:44, three minutes later, against a stated detection target of two minutes. REMEDIATION AND ACTION ITEMS. The flag was reverted at 14:44 and the offending pool initialization was fixed in payment-router v2026.3.1, deployed 2026-03-16. The fail-open override was removed in all regions on 2026-03-15 and a test was added that asserts a breaker-open authorization is treated as a decline. ACT-1: publish flag events to the incident timeline dashboard, owner D. Park, due 2026-03-28. ACT-2: route connection-saturation alerts to the owning service on-call, owner the database team, due 2026-04-04. ACT-3: raise the staging Postgres connection limit and add a pool-leak load test, owner M. Fuentes, due 2026-04-11. ACT-4: add connection saturation to the checkout runbook, owner R. Osei, due 2026-03-21. ACT-5 was proposed, to require a second reviewer for any flag rollout that touches the payment path, but it was not accepted and remains open.",
]
STATE = "\n\n".join(PARAGRAPHS)
QUESTIONS = ["Was the incident declared at severity SEV-2?", "Did the outage affect customers outside eu-central-1?", "Was the root cause a Postgres connection leak in the shadow router?", "Were any duplicate charges issued to customers?", "Was any customer payment data exposed?", "Was the feature flag rolled back before the hotfix was deployed?", "Did automated alerting detect the problem before the first customer report?", "Were all 212 affected orders re-authorized successfully?", "Did the first hypothesis of the team correctly identify the cause?", "Was the fail-open override introduced during this incident?", "Did the fulfilment hold window prevent double shipments?", "Was the connection-count alert routed to the checkout on-call?", "Did database CPU saturation cause the gateway timeouts?", "Was the staging environment able to reproduce the connection leak?", "Did support meet its 15 minute first-response target?", "Were SLA credits approved for the affected enterprise customers?", "Is there an accepted action item requiring a second reviewer for payment-path flag rollouts?", "Did the replica failover fully resolve the 502 responses?", "Was the incident mitigated within two hours of being declared?", "Did the incident result in any chargebacks?", "Did the checkout runbook cover connection saturation before the incident?"]

llm = Jev()
first = llm.decide("The deployment completed at 14:02 UTC. Health checks passed in all three zones.", "Is there evidence that the deployment succeeded?", {"yes": "It succeeded.", "no": "It did not.", "unclear": "Cannot tell."})
print(f"probabilities: {first.probabilities}")
print(f"logits: {first.logits}")
print(f"argmax: {first.argmax}")
print(f"{DIM}{first.input_tokens} input tokens, {first.seconds:.2f}s, p sums to {sum(first.probabilities.values()):.6f}{RESET}")

shared = llm.decide_many(STATE, [(question, ["yes", "no"]) for question in QUESTIONS])
loop = [llm.decide(STATE, question, ["yes", "no"]) for question in QUESTIONS]
flips = sum(a.argmax != b.argmax for a, b in zip(shared, loop))
gap = max(abs(a.probabilities["yes"] - b.probabilities["yes"]) for a, b in zip(shared, loop))
for question, a, b in zip(QUESTIONS, shared, loop):
    print(f"{a.argmax:>3} p(yes)={a.probabilities['yes']:.3f} | {b.argmax:>3} p(yes)={b.probabilities['yes']:.3f} {'disagree' if a.argmax != b.argmax else '        '} {question}")
print(f"{DIM}{len(QUESTIONS)} questions, {len(STATE)} chars of state, {shared[0].input_tokens} input tokens{RESET}")
print(f"{DIM}decide_many {shared[0].seconds:.2f}s, decide loop {sum(d.seconds for d in loop):.2f}s, {flips} argmax disagreements, max |dp| {gap:.4f}{RESET}")
