[project]
name = "qwen27b-jev"
version = "0.1.0"
license-files = ["LICENSE"]
requires-python = "==3.14.*"
dependencies = [
    "click",
    "pytest",
    "torch",
    "transformers",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[tool.uv]
build-backend = { module-root = "", namespace = true }

[tool.pytest.ini_options]
addopts = "-v"

[project.scripts]
qwen27b-jev = "qwen27b_jev:cli"
